version: '3.8'

services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - migrate
    env_file:
      - .env

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservations
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://postgres:admin@postgres:5432/reservations?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    restart: on-failure

volumes:
  postgres_data:
